import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "../providers/authProvider"
import { getServerSession } from "next-auth";
import StoreProvider from "@/lib/store/store-provider";
import Providers from "@/lib/Query/providers";
import {Toaster} from 'react-hot-toast'
import { Poppins } from "next/font/google";
import Script from "next/script";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vital-Aid",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  return (
    <html lang="en">

      <body
        className={`${poppins.className}`}
      >
        <SessionProvider session={session}>
          <StoreProvider>
            <Providers>
            <Toaster position="top-right" reverseOrder={false} />
            <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive" />

              {children}
            </Providers>

          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
